title: Noah Bragg
description: I want to grow and learn in my skills of how to make successful businesses. Maybe you can learn something from joining me on my journey!

url: https://noahbragg.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  twitter: noahwbragg
  email: noahbragg4@gmail.com

google_analytics: "UA-144110918-1"
